### PR TITLE
Add payout proposal component

### PR DESCRIPTION
**Pull request by erak**

### CODE REVIEW

**Comment by EV3RETH** [comment]
It feels like I should be able to choose an option here but I cant.

Screen Shot 2021-10-02 at 3 55 23 PM

**Comment by EV3RETH** [comment]
Lets have some more helpful error text for invalid urls like pointing them to the Sputnik HypeDao. I sat around for a little bit wondering how I was getting the a wrong url until I realized I was trying to use a forum url not the sputnik one

**Comment by EV3RETH** [comment]
Not sure if this was a bug or not but I wasn't able to choose myself as a recipient for the payout

**Comment by EV3RETH** [comment]
Upon completion I'm getting some overlap with the check sign (I'm using Chrome)
Screen Shot 2021-10-02 at 4 04 20 PM

**Review by EV3RETH — CHANGES_REQUESTED** [review]
Looking good! Left a few comments about minor things I'd like changed before we merge this.

**Comment by erak** [comment]
Hey @EV3RETH, so going through your comments ;-)

> It feels like I should be able to choose an option here but I cant.
> 
> Screen Shot 2021-10-02 at 3 55 23 PM

The drop-down is disabled on purpose, since we're only supporting payout proposals for now. I think, I'll add a notice to it, saying stating that.


> Lets have some more helpful error text for invalid urls like pointing them to the Sputnik HypeDao. I sat around for a little bit wondering how I was getting the a wrong url until I realized I was trying to use a forum url not the sputnik one

Ok, that's weird. It should only check for a valid URL in general, not a specific domain. I'll have a look!



> Not sure if this was a bug or not but I wasn't able to choose myself as a recipient for the payout, I kept getting the error message "you are logged in as ev3reth-test.testnet"

Ok, that muss be small boolean-flip in the React component. One can pass a flag to `checkAccountAvailable` in the near hook, to define if the own account should be valid. Here, it should be allowed. It shouldn't when we send HYPE.



> Upon completion I'm getting some overlap with the check sign (I'm using Chrome) Screen Shot 2021-10-02 at 4 04 20 PM

Noted. Will fix!

**Comment by erak** [comment]
@EV3RETH Updated. All the issues mentioned should be fixed now. After merging this, we'll need to set a custom build command on `main` in order to build for Mainnet:
`echo NEAR_ENV=mainnet > .env.local`. The file is picked up by the Next config with this PR.

**Review by EV3RETH — APPROVED** [review]

**Pull request merged**
